BEGIN;

CREATE TABLE IF NOT EXISTS public.comment_attachments (
    attachment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id bigint NOT NULL,
    file_name character varying(255) NOT NULL,
    stored_name character varying(255) NOT NULL,
    mime_type character varying(150),
    file_size bigint,
    uploaded_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comment_attachment_comment
        FOREIGN KEY (comment_id)
        REFERENCES public.ticket_comments(comment_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_comment_attachments_comment
    ON public.comment_attachments (comment_id);

COMMIT;
